//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../images/
:icons: font

== Developer Section

This part of the Apache PLC4X is dedicated to providing information to people wanting to build PLC4X and hopefully also start contributing to this awesome project.

=== Getting Started

We have tried to make the PLC4X build experience as smooth as possible and reduced the number of required third-party tools to an absolute minimum.

The full PLC4X build, however, includes not only the `Java` libraries, but also the `C++`, `Python` and `C#` libraries as well as `Docker` images on `Linux`, `Mac` and `Windows`.

As a starting point, you will basically need a `Java VM` of at least `Java 11`.

If you use the `Maven-Wrapper` you don't even need to install `Maven`. The build will automatically fetch the right version for you.

As part of the build process, we have an initial step that will perform a `prerequisite check`. Depending on the activated modules, it will check if all preconditions are met and tell you what is missing.

For more details, please have a look at the link:preparing/index.html[Preparing your Computer] page.

=== Building PLC4X

We have a dedicated page on link:building.html[Building PLC4X]. Please read this page for information about how to build Apache PLC4X.

=== Contributing

If you want to work on Apache PLC4X to fix bugs, add features or start contributing in general, please have a look at our link:contributing.html[Contributing] page. It should contain all the information you need.

=== Getting Help

The primary source for getting help is definitely our project mailing list dev@plc4x.apache.org.

You can search previous content in our link:++https://lists.apache.org/list.html?dev@plc4x.apache.org++[Mail Archive]

To post to the list, you must first subscribe by sending an empty email to dev-subscribe@plc4x.apache.org.
